/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.prgarnett.notedatabase;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import org.neo4j.driver.v1.Driver;
import org.neo4j.driver.v1.Session;
import org.neo4j.driver.v1.StatementResult;

/**
 *
 * @author philipgarnett
 */
public class NewNotePanel extends javax.swing.JPanel 
{
    private final DateFormat dateFormat;
    private final Date date;
    private final Driver driver;
    private final Session session;
    private final JFrame thisFrame;
    private List<String> keywords;
    private List<String> associations;
    
    /**
     * Creates new form NewNotePanel
     * @param driver
     */
    public NewNotePanel(Driver driver, JFrame thisFrame) 
    {
        this.driver = driver;
        this.thisFrame = thisFrame;
        this.session = driver.session();
        dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        date = new Date();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        notesText = new javax.swing.JTextArea();
        createButton = new javax.swing.JButton();
        keywordsButton = new javax.swing.JButton();
        titleField = new javax.swing.JTextField();
        noteTitleLabel = new javax.swing.JLabel();
        linkNotesButton = new javax.swing.JButton();
        panelTitle = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeTextField = new javax.swing.JTextField();

        setAutoscrolls(true);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notesText.setColumns(20);
        notesText.setRows(5);
        jScrollPane1.setViewportView(notesText);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 550, 240));

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        keywordsButton.setText("Keywords");
        keywordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordsButtonActionPerformed(evt);
            }
        });
        add(keywordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));
        add(titleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, -1));

        noteTitleLabel.setText("Note Title:");
        add(noteTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        linkNotesButton.setLabel("Link Notes");
        linkNotesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkNotesButtonActionPerformed(evt);
            }
        });
        add(linkNotesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        panelTitle.setText("Creat a New Note");
        add(panelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        dateLabel.setText("Date:");
        add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        dateField.setText(dateFormat.format(date));
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });
        add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 150, -1));

        typeLabel.setText("Node Type");
        add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));
        add(typeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void keywordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordsButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_keywordsButtonActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        String propertyList = "Title: '" + titleField.getText() + "'" 
                + ",Date: '" + dateField.getText() + "'"
                + ",Content: '" + notesText.getText() + "'";

        StatementResult result = session.run( "create (newNode:"+ typeTextField.getText() + "{" + propertyList + "})");
        
//        System.out.println("Something should have happened");
        session.close();
        this.thisFrame.dispose();
    }//GEN-LAST:event_createButtonActionPerformed

    private void linkNotesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkNotesButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_linkNotesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keywordsButton;
    private javax.swing.JButton linkNotesButton;
    private javax.swing.JLabel noteTitleLabel;
    private javax.swing.JTextArea notesText;
    private javax.swing.JLabel panelTitle;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField typeTextField;
    // End of variables declaration//GEN-END:variables
}
